<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216181155 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE reina.user_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.cupones_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.memoria_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.viajes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.viajeitem_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.habito_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.habitolog_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.entretenimiento_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE reina.foto_id_seq CASCADE');
        $this->addSql('CREATE TABLE dinosaurs_project."user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(150) NOT NULL, password VARCHAR(800) NOT NULL, role JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE reina.cupones DROP CONSTRAINT cupones_id_user_fkey');
        $this->addSql('ALTER TABLE reina.foto DROP CONSTRAINT foto_id_memoria_fkey');
        $this->addSql('ALTER TABLE reina.habitolog DROP CONSTRAINT habitolog_id_habito_fkey');
        $this->addSql('ALTER TABLE reina.viajeitem DROP CONSTRAINT viajeitem_id_viajes_fkey');
        $this->addSql('DROP TABLE dinosaurs_project."user"');
        $this->addSql('DROP TABLE dinosaurs');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE reina.cupones');
        $this->addSql('DROP TABLE reina.entretenimiento');
        $this->addSql('DROP TABLE reina.foto');
        $this->addSql('DROP TABLE reina.habito');
        $this->addSql('DROP TABLE reina.habitolog');
        $this->addSql('DROP TABLE reina.memoria');
        $this->addSql('DROP TABLE reina."user"');
        $this->addSql('DROP TABLE reina.viajeitem');
        $this->addSql('DROP TABLE reina.viajes');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER image TYPE VARCHAR(800)');
        $this->addSql('ALTER TABLE dinosaurs_project.category_dinosaur ADD PRIMARY KEY (id_category, id_dinosaur)');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA reina');
        $this->addSql('CREATE SEQUENCE reina.user_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.cupones_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.memoria_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.viajes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.viajeitem_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.habito_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.habitolog_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.entretenimiento_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE reina.foto_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE dinosaurs_project."user" (id INT NOT NULL, email VARCHAR(150) NOT NULL, password VARCHAR(800) NOT NULL, role VARCHAR(500) DEFAULT \'0\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE dinosaurs (id INT NOT NULL, name VARCHAR(150) DEFAULT NULL, weight VARCHAR(100) DEFAULT NULL, height VARCHAR(100) DEFAULT NULL, lenght VARCHAR(100) DEFAULT NULL, diet INT DEFAULT NULL, period INT DEFAULT NULL, existed VARCHAR(255) DEFAULT NULL, region VARCHAR(200) DEFAULT NULL, type INT DEFAULT NULL, description VARCHAR(10000) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT NOT NULL, email VARCHAR(150) DEFAULT NULL, password VARCHAR(150) DEFAULT NULL, rol INT DEFAULT 0, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reina.cupones (id INT DEFAULT nextval(\'reina.cupones_id_seq\'::regclass) NOT NULL, titulo VARCHAR(150) DEFAULT NULL, descripcion TEXT DEFAULT NULL, estado VARCHAR(150) DEFAULT NULL, fecha_validez TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, id_user INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE9779766B3CA4B ON reina.cupones (id_user)');
        $this->addSql('CREATE TABLE reina.entretenimiento (id INT DEFAULT nextval(\'reina.entretenimiento_id_seq\'::regclass) NOT NULL, titulo VARCHAR(150) DEFAULT NULL, tipo VARCHAR(150) DEFAULT NULL, estado VARCHAR(150) DEFAULT NULL, puntuacion INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reina.foto (id INT DEFAULT nextval(\'reina.foto_id_seq\'::regclass) NOT NULL, url TEXT DEFAULT NULL, archivo TEXT DEFAULT NULL, id_memoria INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_652EDC732AB1AC75 ON reina.foto (id_memoria)');
        $this->addSql('CREATE TABLE reina.habito (id INT DEFAULT nextval(\'reina.habito_id_seq\'::regclass) NOT NULL, nombre VARCHAR(150) DEFAULT NULL, objetivo_semanal VARCHAR(300) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reina.habitolog (id INT DEFAULT nextval(\'reina.habitolog_id_seq\'::regclass) NOT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cantidad INT DEFAULT NULL, id_habito INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2EFD0CEF9777C898 ON reina.habitolog (id_habito)');
        $this->addSql('CREATE TABLE reina.memoria (id INT DEFAULT nextval(\'reina.memoria_id_seq\'::regclass) NOT NULL, titulo VARCHAR(150) DEFAULT NULL, fecha TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, descripcion TEXT DEFAULT NULL, ubicacion VARCHAR(150) DEFAULT NULL, tipo VARCHAR(150) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reina."user" (id INT DEFAULT nextval(\'reina.user_id_seq\'::regclass) NOT NULL, email VARCHAR(150) NOT NULL, password VARCHAR(800) NOT NULL, roles VARCHAR(500) DEFAULT \'0\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reina.viajeitem (id INT DEFAULT nextval(\'reina.viajeitem_id_seq\'::regclass) NOT NULL, dia TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, actividad VARCHAR(150) DEFAULT NULL, coste NUMERIC(5, 2) DEFAULT NULL, id_viajes INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5E82F438C9F08E5A ON reina.viajeitem (id_viajes)');
        $this->addSql('CREATE TABLE reina.viajes (id INT DEFAULT nextval(\'reina.viajes_id_seq\'::regclass) NOT NULL, destino VARCHAR(150) DEFAULT NULL, fecha_inicio TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fecha_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, presupuesto NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE reina.cupones ADD CONSTRAINT cupones_id_user_fkey FOREIGN KEY (id_user) REFERENCES reina."user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reina.foto ADD CONSTRAINT foto_id_memoria_fkey FOREIGN KEY (id_memoria) REFERENCES reina.memoria (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reina.habitolog ADD CONSTRAINT habitolog_id_habito_fkey FOREIGN KEY (id_habito) REFERENCES reina.habito (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reina.viajeitem ADD CONSTRAINT viajeitem_id_viajes_fkey FOREIGN KEY (id_viajes) REFERENCES reina.viajes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE dinosaurs_project."user"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER image TYPE TEXT');
        $this->addSql('ALTER TABLE dinosaurs_project.category_dinosaur DROP CONSTRAINT dinosaurs_project.category_dinosaur_pkey');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id DROP IDENTITY');
    }
}
