<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260210141120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE dinosaurs_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE users_id_seq CASCADE');
        $this->addSql('CREATE TABLE dinosaurs_project."user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(150) NOT NULL, password VARCHAR(800) NOT NULL, role JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('DROP TABLE dinosaurs_project."user"');
        $this->addSql('DROP TABLE dinosaurs');
        $this->addSql('DROP TABLE users');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER image TYPE VARCHAR(800)');
        $this->addSql('ALTER TABLE dinosaurs_project.category_dinosaur ADD PRIMARY KEY (id_category, id_dinosaur)');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking DROP CONSTRAINT ranking_id_category_fkey');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ADD CONSTRAINT FK_A51E3C785697F554 FOREIGN KEY (id_category) REFERENCES dinosaurs_project.category (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER comment TYPE VARCHAR(10000)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE dinosaurs_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE users_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE dinosaurs_project."user" (id INT DEFAULT nextval(\'dinosaurs_project.user_id_seq\'::regclass) NOT NULL, email VARCHAR(150) NOT NULL, password VARCHAR(800) NOT NULL, role VARCHAR(500) DEFAULT \'0\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE dinosaurs (id INT DEFAULT nextval(\'dinosaurs_id_seq\'::regclass) NOT NULL, name VARCHAR(150) DEFAULT NULL, weight VARCHAR(100) DEFAULT NULL, height VARCHAR(100) DEFAULT NULL, lenght VARCHAR(100) DEFAULT NULL, diet INT DEFAULT NULL, period INT DEFAULT NULL, existed VARCHAR(255) DEFAULT NULL, region VARCHAR(200) DEFAULT NULL, type INT DEFAULT NULL, description VARCHAR(10000) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT DEFAULT nextval(\'users_id_seq\'::regclass) NOT NULL, email VARCHAR(150) DEFAULT NULL, password VARCHAR(150) DEFAULT NULL, rol INT DEFAULT 0, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE dinosaurs_project."user"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id SET DEFAULT nextval(\'dinosaurs_project.category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.category ALTER image TYPE TEXT');
        $this->addSql('ALTER TABLE dinosaurs_project.category_dinosaur DROP CONSTRAINT dinosaurs_project.category_dinosaur_pkey');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id SET DEFAULT nextval(\'dinosaurs_project.dinosaur_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dinosaurs_project.dinosaur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking DROP CONSTRAINT FK_A51E3C785697F554');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id SET DEFAULT nextval(\'dinosaurs_project.ranking_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking ADD CONSTRAINT ranking_id_category_fkey FOREIGN KEY (id_category) REFERENCES dinosaurs_project.category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id SET DEFAULT nextval(\'dinosaurs_project.ranking_dinosaur_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dinosaurs_project.ranking_dinosaur ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id SET DEFAULT nextval(\'dinosaurs_project.review_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE dinosaurs_project.review ALTER comment TYPE TEXT');
    }
}
